### ISSUE TITLE
Prepare a clean C380-HQ codebase, aside from any sub-projects

### ISSUE THREAD

**Issue by kdidenko** [C380/c380.github.io#4]
### 🔬 Overview

1. **First of all**, currently the entire repository's codebase is all located within the only **one branch** - [**`main`**](https://github.com/C380/c380.github.io). This includes the static `html` templates for [**`C380.center`**](https://c380.github.io/) website (_this repository was actually created for_), along with third-party code added due to the **_possible_** plans for further joining the main website as an "**`Online Services`**" section.

2. **Additionally**, the situation described above affected not only the repository's files & directories layout structure, but it also historically has been reflected in the [**`commits history`**](https://github.com/C380/c380.github.io/commits/master) log.
Actually, only first four commits make sense in terms of **initial codebase image**, while the rest of code must be moved to the separate branch, also cleaning up the `commit log` by using the native `git merge `/ `rebase` tools in the proper way.

### ✅ Task Summary

- [ ] Go through the [**`commits history`**](https://github.com/C380/c380.github.io/commits/master) and mark any third-party source code to be moved to it's own branches.
- [ ] Perform the [**`git rebase`**](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) against the codebase at  [**`main`**](https://github.com/C380/c380.github.io) branch in the way the previously marked commits to be moved on top of the history log.
- [ ] Create the corresponding branches for the third-party code and move all marked commits there.
- [ ] Review the C380-WebHQ Codebase remained in the `main` branch. Perform any clean-up actions if required.
